try to fail when build scripts has errors

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -95,7 +95,6 @@ jobs:
       - name: Run code formatting (clang-format and clang-tidy)
         run: docker run
           --rm ${{ env.CUR_DOCKER_TAG }}
-          -e "GITHUB_EVENT_PATH:$GITHUB_EVENT_PATH"
           bash -c "cd /home/astro-dev/src/ && sudo chmod u+x entrypoint.sh && source entrypoint.sh"
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
@@ -121,9 +120,9 @@ jobs:
         run: docker run --rm ${{ env.CUR_DOCKER_TAG }} bash -c " \\
             cd /home/astro-dev/src/; \\
             source build_scripts/build.sh 2> >(tee err.log >&2); \\
-            if [ -s err.log ]; then \\
-              echo "Build failed due to output in stderr."; \\
-              cat err.log; \\
-              exit 1 \\
+            if [ -s err.log ]; then
+              echo "Build failed due to output in stderr.";
+              cat err.log;
+              exit 1
             fi \\
           "
