try to fail when build scripts has errors

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -85,7 +85,7 @@ jobs:
         run: echo "CUR_DOCKER_TAG=${{ secrets.DOCKER_USERNAME }}${{ needs.build-dev-container.outputs.cur_docker_tag }}" >> $GITHUB_ENV
 
       - name: Run code formatting (clang-format and clang-tidy)
-        run: docker run --rm ${{ env.CUR_DOCKER_TAG }} bash -c "cd /home/astro-dev/src/ && chmod u+x entrypoint.sh && source entrypoint.sh"
+        run: docker run --rm ${{ env.CUR_DOCKER_TAG }} bash -c "cd /home/astro-dev/src/ && sudo chmod u+x entrypoint.sh && source entrypoint.sh"
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
 
@@ -108,11 +108,11 @@ jobs:
       - name: Build our source code in our developer container
         run: |
           docker run --rm ${{ env.CUR_DOCKER_TAG }} bash -c "
-          cd /home/astro-dev/src/;
-          source build_scripts/build.sh 2> err.log;
-          if [ -s err.log ]; then
-            echo "Build failed due to output in stderr.";
-            cat err.log;
-            exit 1
-          fi
+            cd /home/astro-dev/src/;
+            source build_scripts/build.sh 2> err.log;
+            if [ -s err.log ]; then
+              echo "Build failed due to output in stderr.";
+              cat err.log;
+              exit 1
+            fi
           "
