try to fail when build scripts has errors

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -60,6 +60,14 @@ jobs:
     #     echo "COPY .github/workflows/ci/ /home/astro-dev/src/" >> .github/workflows/ci/Dockerfile
 
     # - name: Build the developer container image
+      # run: |
+        # docker build \
+    #     --file .github/workflows/ci/Dockerfile \
+    #     --tag ${{ env.CUR_DOCKER_TAG }} \
+    #     --cache-to type=inline \
+    #     --cache-from=${{ env.CACHE_DOCKER_TAG }} \
+    #     .
+
     #   run: docker build
     #     --file .github/workflows/ci/Dockerfile
     #     --tag ${{ env.CUR_DOCKER_TAG }}
@@ -85,7 +93,10 @@ jobs:
         run: echo "CUR_DOCKER_TAG=${{ secrets.DOCKER_USERNAME }}${{ needs.build-dev-container.outputs.cur_docker_tag }}" >> $GITHUB_ENV
 
       - name: Run code formatting (clang-format and clang-tidy)
-        run: docker run --rm ${{ env.CUR_DOCKER_TAG }} bash -c "cd /home/astro-dev/src/ && sudo chmod u+x entrypoint.sh && source entrypoint.sh"
+        run: docker run
+          --rm ${{ env.CUR_DOCKER_TAG }}
+          -e "GITHUB_EVENT_PATH:$GITHUB_EVENT_PATH"
+          bash -c "cd /home/astro-dev/src/ && sudo chmod u+x entrypoint.sh && source entrypoint.sh"
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
           GITHUB_EVENT_PATH: ${{ env.GITHUB_EVENT_PATH }}
@@ -107,12 +118,12 @@ jobs:
         run: echo "CUR_DOCKER_TAG=${{ secrets.DOCKER_USERNAME }}${{ needs.build-dev-container.outputs.cur_docker_tag }}" >> $GITHUB_ENV
 
       - name: Build our source code in our developer container
-        run: docker run --rm ${{ env.CUR_DOCKER_TAG }} bash -c " \
-            cd /home/astro-dev/src/; \
-            source build_scripts/build.sh 2> >(tee err.log >&2); \
-            if [ -s err.log ]; then \
-              echo "Build failed due to output in stderr."; \
-              cat err.log; \
-              exit 1 \
-            fi \
+        run: docker run --rm ${{ env.CUR_DOCKER_TAG }} bash -c " \\
+            cd /home/astro-dev/src/; \\
+            source build_scripts/build.sh 2> >(tee err.log >&2); \\
+            if [ -s err.log ]; then \\
+              echo "Build failed due to output in stderr."; \\
+              cat err.log; \\
+              exit 1 \\
+            fi \\
           "
