try to fail when build scripts has errors

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -88,6 +88,7 @@ jobs:
         run: docker run --rm ${{ env.CUR_DOCKER_TAG }} bash -c "cd /home/astro-dev/src/ && sudo chmod u+x entrypoint.sh && source entrypoint.sh"
         env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+          GITHUB_EVENT_PATH: ${{ env.GITHUB_EVENT_PATH }}
 
       # - name: Clang Code Formatter
       #   run: source .github/workflows/entrypoint.sh
@@ -106,13 +107,12 @@ jobs:
         run: echo "CUR_DOCKER_TAG=${{ secrets.DOCKER_USERNAME }}${{ needs.build-dev-container.outputs.cur_docker_tag }}" >> $GITHUB_ENV
 
       - name: Build our source code in our developer container
-        run: |
-          docker run --rm ${{ env.CUR_DOCKER_TAG }} bash -c "
-            cd /home/astro-dev/src/;
-            source build_scripts/build.sh 2> >(tee err.log >&2);
-            if [ -s err.log ]; then
-              echo "Build failed due to output in stderr.";
-              cat err.log;
-              exit 1
-            fi
+        run: docker run --rm ${{ env.CUR_DOCKER_TAG }} bash -c " \
+            cd /home/astro-dev/src/; \
+            source build_scripts/build.sh 2> >(tee err.log >&2); \
+            if [ -s err.log ]; then \
+              echo "Build failed due to output in stderr."; \
+              cat err.log; \
+              exit 1 \
+            fi \
           "
